# Dracula theme
# https://draculatheme.com/

background = "#282a36"
foreground = "#f8f8f2"
cursor_bg = "#44475a"
selection_bg = "#44475a"
directory = "#bd93f9"
header_bg = "#21222c"
status_bg = "#21222c"
border = "#6272a4"
border_focused = "#ff79c6"
icon_folder = "\uf07b"
icon_file = "\uf15b"
