# One Dark theme (Atom)
# https://github.com/atom/one-dark-syntax

background = "#282c34"
foreground = "#abb2bf"
cursor_bg = "#3e4451"
selection_bg = "#3e4451"
directory = "#61afef"
header_bg = "#21252b"
status_bg = "#21252b"
border = "#4b5263"
border_focused = "#528bff"
icon_folder = "\uf07b"
icon_file = "\uf15b"
